# Generated by Django 3.1.3 on 2020-12-16 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyLibrary', '0002_book_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyLibrary.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyLibrary.writer'),
            preserve_default=False,
        ),
    ]
